### ISSUE TITLE
Not working with solid-slack-bridge

### ISSUE THREAD

**Issue by michielbdejong** [solid-contrib/pivot#27]
When trying to use [solid-slack-bridge](https://github.com/pondersource/solid-slack-bridge) with a Pivot instance, it logs:
```
> solid-slack-bridge@1.0.0 start
> node dist/index.js

[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[13:36:30.980] INFO (39229): ⚡️ Bolt app running on port http://localhost:7000
[13:36:30.983] INFO (39229): Express app running on port http://localhost:8000
[INFO]  socket-mode:SocketModeClient:0 Now connected to Slack
(node:39229) DraftWarning: The DPoP APIs implements an IETF draft (https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html). Breaking draft implementations are included as minor versions of the openid-client library, therefore, the ~ semver operator should be used and close attention be payed to library changelog as well as the drafts themselves.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/openid-client/lib/helpers/process_response.js:38
      throw new OPError(response.body, response);
            ^

OPError: invalid_grant (grant request is invalid)
    at processResponse (/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/openid-client/lib/helpers/process_response.js:38:13)
    at Client.grant (/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/openid-client/lib/client.js:1327:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.callback (/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/openid-client/lib/client.js:476:24)
    at async AuthCodeRedirectHandler.handle (/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/@inrupt/solid-client-authn-node/dist/index.js:411:26)
    at async ClientAuthentication.handleIncomingRedirect (/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/@inrupt/solid-client-authn-node/dist/index.js:55:34)
    at async Session.handleIncomingRedirect (/Users/michiel/gh/pondersource/solid-slack-bridge/node_modules/@inrupt/solid-client-authn-node/dist/index.js:738:35) {
  error: 'invalid_grant',
  error_description: 'grant request is invalid'
}

Node.js v20.9.0
```

**Comment by michielbdejong** [comment]
Hm, maybe this is not a problem with Pivot because https://github.com/tubsproject/solid-client works.
